"""WAF 检测器 — 通过响应差异分析识别目标使用的 WAF 类型"""
import re
import time
import requests


# WAF 特征库: {名称: {'vendor': 厂商, 'headers': [响应头匹配], 'body': [响应体关键词],
#             'status_codes': [拦截状态码], 'score': 基础分}}
WAF_SIGNATURES = {
    'Cloudflare': {
        'vendor': 'Cloudflare Inc.',
        'headers': ['cf-ray', 'cf-cache-status', 'cf-request-id', '__cfduid'],
        'body': ['cloudflare', 'cf-browser-verification', 'attention required'],
        'status_codes': [403, 503],
        'score': 90,
    },
    'AWS WAF': {
        'vendor': 'Amazon Web Services',
        'headers': ['x-amzn-waf-action', 'x-amz-cf-id', 'x-amzn-requestid'],
        'body': ['aws waf', 'request blocked'],
        'status_codes': [403],
        'score': 85,
    },
    'Akamai': {
        'vendor': 'Akamai Technologies',
        'headers': ['x-akamai-transformed', 'akamai-origin-hop', 'x-akamai-request-id'],
        'body': ['akamai', 'reference #', 'access denied'],
        'status_codes': [403],
        'score': 85,
    },
    'Sucuri': {
        'vendor': 'Sucuri Inc.',
        'headers': ['x-sucuri-id', 'x-sucuri-cache'],
        'body': ['sucuri', 'access denied', 'blocked by sucuri'],
        'status_codes': [403],
        'score': 90,
    },
    'Imperva': {
        'vendor': 'Imperva Inc.',
        'headers': ['x-iinfo', 'x-cdn'],
        'body': ['imperva', 'incapsula', '_imp_apg_r'],
        'status_codes': [403, 999],
        'score': 85,
    },
    'ModSecurity': {
        'vendor': 'Trustwave / Open Source',
        'headers': [],
        'body': ['mod_security', 'modsecurity', 'not acceptable', 'this error was generated by mod_security'],
        'status_codes': [403, 406],
        'score': 80,
    },
    'F5 BIG-IP ASM': {
        'vendor': 'F5 Networks',
        'headers': ['bigipserver', 'f5-bigip', 'x-wa-info'],
        'body': ['bigip', 'f5 trafficshield', 'the requested url was rejected'],
        'status_codes': [403],
        'score': 80,
    },
    'FortiWeb': {
        'vendor': 'Fortinet',
        'headers': [],
        'body': ['fortiweb', 'fortigate', 'fortinet', 'blocked by fortiguard'],
        'status_codes': [403, 412],
        'score': 85,
    },
    'Barracuda': {
        'vendor': 'Barracuda Networks',
        'headers': ['barra'],
        'body': ['barracuda', 'you have been blocked', 'bwaf'],
        'status_codes': [403],
        'score': 80,
    },
    'Wordfence': {
        'vendor': 'Defiant Inc.',
        'headers': [],
        'body': ['wordfence', 'generated by wordfence', 'your access has been blocked'],
        'status_codes': [403, 503],
        'score': 90,
    },
    'SiteLock': {
        'vendor': 'SiteLock LLC',
        'headers': [],
        'body': ['sitelock', 'blocked by sitelock'],
        'status_codes': [403],
        'score': 85,
    },
    'Reblaze': {
        'vendor': 'Reblaze Technologies',
        'headers': ['x-rblaze-cache'],
        'body': ['reblaze'],
        'status_codes': [403],
        'score': 85,
    },
    '腾讯云 WAF': {
        'vendor': '腾讯云',
        'headers': ['x-tencent-uui'],
        'body': ['waf.tencent', 'tencent waf', '请求已被拦截'],
        'status_codes': [403, 524],
        'score': 90,
    },
    '阿里云 WAF': {
        'vendor': '阿里云',
        'headers': [],
        'body': ['aliyunwaf', 'yundun', '安全威胁', '请求已被阻断', 'alibaba'],
        'status_codes': [403, 405],
        'score': 90,
    },
    '长亭雷池': {
        'vendor': '长亭科技',
        'headers': [],
        'body': ['safeline', '雷池', 'chaitin', '请求被阻断'],
        'status_codes': [403, 463],
        'score': 90,
    },
}

# 探测 payload — 渐进式恶意请求，用于触发 WAF 拦截
PROBE_PAYLOADS = [
    "?id=1",
    "?id=1' OR '1'='1",
    "?id=1 UNION SELECT NULL--",
    "?q=<script>alert(1)</script>",
    "?file=../../../etc/passwd",
]


class WAFDetector:
    """WAF 检测器 — 通过响应差异分析识别目标 WAF"""

    def __init__(self, timeout=10):
        self.timeout = timeout
        self.session = requests.Session()
        self.session.verify = False
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
        })

    def detect(self, url):
        """检测目标 URL 使用的 WAF

        Returns:
            dict: {
                'detected': bool,
                'waf_name': str,
                'vendor': str,
                'confidence': int (0-100),
                'evidence': list[str],
                'bypass_suggestions': list[str],
                'details': list[dict]  # 所有可能匹配的 WAF
            }
        """
        # 第一步：获取基线响应
        baseline = self._get_baseline(url)
        if not baseline:
            return {'detected': False, 'waf_name': '', 'vendor': '', 'confidence': 0,
                    'evidence': ['无法连接到目标'], 'bypass_suggestions': [], 'details': []}

        # 第二步：发送探测 payload
        probe_results = []
        for payload in PROBE_PAYLOADS:
            try:
                probe_url = url.rstrip('/') + payload if '?' not in url else url + '&' + payload[1:]
                resp = self.session.get(probe_url, timeout=self.timeout, allow_redirects=False)
                probe_results.append({
                    'payload': payload,
                    'status_code': resp.status_code,
                    'headers': dict(resp.headers),
                    'body': resp.text[:5000],
                    'elapsed': resp.elapsed.total_seconds(),
                })
            except Exception:
                continue

        # 第三步：差异分析 + 签名匹配
        matches = self._analyze_differences(baseline, probe_results)

        # 按置信度排序
        matches.sort(key=lambda x: x['confidence'], reverse=True)

        if matches:
            top = matches[0]
            return {
                'detected': True,
                'waf_name': top['name'],
                'vendor': top['vendor'],
                'confidence': top['confidence'],
                'evidence': top['evidence'],
                'bypass_suggestions': self._suggest_bypass(top['name']),
                'details': matches,
            }

        # 没有精确匹配，但检查是否有拦截行为
        blocked = any(r['status_code'] in (403, 406, 418, 429, 501, 503, 999) for r in probe_results)
        if blocked:
            return {
                'detected': True,
                'waf_name': '未知 WAF',
                'vendor': '未知',
                'confidence': 50,
                'evidence': ['探测请求被拦截，但无法识别具体 WAF 类型'],
                'bypass_suggestions': ['尝试 URL 编码绕过', '尝试大小写混淆', '尝试添加自定义 Header'],
                'details': [],
            }

        return {'detected': False, 'waf_name': '', 'vendor': '', 'confidence': 0,
                'evidence': [], 'bypass_suggestions': [], 'details': []}

    def _get_baseline(self, url):
        """获取正常请求的基线响应"""
        try:
            resp = self.session.get(url, timeout=self.timeout, allow_redirects=True)
            return {
                'status_code': resp.status_code,
                'headers': {k.lower(): v for k, v in resp.headers.items()},
                'body': resp.text[:5000],
                'body_len': len(resp.text),
                'elapsed': resp.elapsed.total_seconds(),
            }
        except Exception:
            return None

    def _analyze_differences(self, baseline, probe_results):
        """对比基线和探测响应，匹配 WAF 签名"""
        matches = []
        base_headers = set(baseline['headers'].keys())

        for name, sig in WAF_SIGNATURES.items():
            evidence = []
            score = 0

            for probe in probe_results:
                resp_headers = {k.lower(): v for k, v in probe['headers'].items()}
                resp_body = probe['body'].lower()

                # 检查响应头匹配
                for h in sig['headers']:
                    if h.lower() in resp_headers:
                        evidence.append(f'响应头匹配: {h}: {resp_headers[h.lower()][:80]}')
                        score += 30

                # 检查响应体关键词
                for keyword in sig['body']:
                    if keyword.lower() in resp_body:
                        evidence.append(f'响应体匹配: "{keyword}"')
                        score += 20

                # 检查状态码
                if probe['status_code'] in sig['status_codes']:
                    if probe['status_code'] != baseline['status_code']:
                        evidence.append(f'状态码异常: {baseline["status_code"]} → {probe["status_code"]}')
                        score += 15

            if score > 0:
                confidence = min(sig['score'] + score - 40, 100)
                matches.append({
                    'name': name,
                    'vendor': sig['vendor'],
                    'confidence': max(confidence, 30),
                    'evidence': list(set(evidence)),
                })

        return matches

    @staticmethod
    def _suggest_bypass(waf_name):
        """根据 WAF 类型推荐绕过策略"""
        common = ['URL 编码', '大小写混淆', '添加 X-Forwarded-For 头']
        specific = {
            'Cloudflare': ['尝试 HTTP/2 协议', '使用 chunked 传输编码', 'Unicode 编码'],
            'AWS WAF': ['参数污染', 'JSON 格式提交', '修改 Content-Type'],
            'ModSecurity': ['注释插入 (SEL/**/ECT)', '空字节前缀', '双重 URL 编码'],
            'Wordfence': ['添加 Referer 头', '使用 POST 方法', '延迟请求间隔'],
            '阿里云 WAF': ['宽字节编码', '混合编码', 'HTTP 参数分块'],
            '腾讯云 WAF': ['Unicode 变体', '路径混淆', 'Header 伪造'],
            '长亭雷池': ['协议层绕过', '分块传输', '多阶段请求'],
        }
        return specific.get(waf_name, common)
